// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMotorsProject.Repository.Context;

namespace WebMotorsProject.Repository.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20191008113016_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebMotorsProject.Repository.Entity.Anuncio", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Marca")
                        .HasColumnName("marca");

                    b.Property<long>("KM")
                        .HasColumnName("quilometragem");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo");

                    b.Property<string>("Observacao")
                        .HasColumnName("observacao");

                    b.Property<string>("Versao")
                        .HasColumnName("versao");

                    b.Property<int>("Ano")
                        .HasColumnName("ano");

                    b.HasKey("Id");

                    b.ToTable("tb_AnuncioWebmotors");
                });
#pragma warning restore 612, 618
        }
    }
}
